# SETUP
baseurl = "/"
DefaultContentLanguage = "es"
publishdir = "public"
canonifyUrls = "true"
disableKinds = [
    "RSS",
    "taxonomy",
    "taxonomyTerm",
] # disable hugo's content that we don't need...

title = "BG Consultora" # page title -> see ./layouts/partials/head.html

googleAnalytics = "" # if needed...

[author]
name = "BG Consultora"
email = "info@bgconsultora.com.ar"

[params]
description = "BG Consultora" # page description -> see ./layouts/partials/head.html
images = [
] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

# these items will be rendered 1. into a tooltip in the navbar and 2. into the footer - consider that there's limited space when adding more items -> see ./layouts/partials
[[params.social]]
title = "Instagram"
url = "https://www.instagram.com/bg_consultora.arg" # add your twitter handle
[[params.social]]
title = "LinkedIn"
url = "https://www.linkedin.com/company/bg-consultora-arg/about/" # add your linkedin profile URL
